##
## Script for plotting the volatility data generated by the C++
## code
##

setwd("~/drive/concordia/2015-2016/1_fall2015/macf402/assignment3/")
implied_vols <- read.csv("./data/output/q1_implied_vols.csv", stringsAsFactors = F)

## get volatility data 
callvols <- implied_vols$call_imp_vol
putvols <- implied_vols$put_imp_vol

## begin plotting smile
pdf("./plots/q1/smile.pdf", height = 4.75, width = 9.5)
par(mfrow = c(1,2), oma = c(0, 0, 2, 0)) # 
## OTM OPTIONS: plot volatility smile for the largest N computed
otm_callvols <- callvols
otm_callvols[which(unique(implied_vols$moneyness) <= 1)] <- NaN
otm_putvols <- putvols
otm_putvols[which(unique(implied_vols$moneyness) >= 1)] <- NaN
# endpoints for y axis, consider the highest/lowest volatilities & round them up/down
lo <- floor(min(otm_callvols, otm_putvols, na.rm = T)*100)/100
hi <- ceiling(max(otm_callvols, otm_putvols, na.rm = T)*100)/100 

plot(otm_callvols ~ unique(implied_vols$strike), 
     lwd = 2, type = 'b', ylim = c(lo, hi),
     xlab = "Strike", ylab = "Implied Volatility", main = "Volatilities: OTM Options",
     xaxt = "n", yaxt = "n") # xaxt = 'n', yaxt = 'n', suppress drawing axis values
axis(2, at = seq(lo, hi, 0.05), las = 1) # draw y axis ticks from lo to hi every 0.05
axis(1, at = unique(implied_vols$strike), las = 1) # draw y axis ticks from lo to hi every 0.05
lines(otm_putvols ~ unique(implied_vols$strike), lwd = 2, pch = 24, type = 'b', yaxt = "n")
legend("topright", legend = c("Call","Put"), pch = c(21,24), text.font = 2)

## plot ALL strikes regardless of moneyness
# endpoints for y axis, consider the highest and lowest volatilities
lo <- floor(min(callvols, putvols, na.rm = T)*100)/100
hi <- ceiling(max(callvols, putvols, na.rm = T)*100)/100

## ALL OPTIONS: smile for largest N
plot(callvols ~ unique(implied_vols$strike), 
     lwd = 2, type = 'b', ylim = c(lo, hi),
     xlab = "Strike", ylab = "Implied Volatility", main = "Volatilities: All Options",
     xaxt = "n", yaxt = "n") # xaxt = 'n', yaxt = 'n', suppress drawing axis values
axis(2, at = seq(lo, hi, 0.05), las = 1) # draw y axis ticks from lo to hi every 0.05
axis(1, at = unique(implied_vols$strike), las = 1) # draw y axis ticks from lo to hi every 0.05
lines(putvols ~ unique(implied_vols$strike), lwd = 2, pch = 24, type = 'b', yaxt = "n")
legend("topright", legend = c("Call","Put"), pch = c(21,24), text.font = 2)
mtext("Volatility Smile: Black-Scholes", outer = T, cex = 1.25)
dev.off() 